name: linting, testing, building

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  pipeline:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [ 17.x ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Node.js environment ${{ matrix.node-version }}
      - uses: actions/setup-node@v1.4.3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
        run: npm install

      - name: build production project
        run: npm run build:prod

      - name: linting typescript
        run: npm run lint:ts

      - name: linting styles
        run: npm run lint:scss

      - name: unit testing
        run: npm run test:unit
