name: linting, testing, building

on: [push]

jobs:
  pipeline:
    strategy:
      matrix:
        node-version: [ 17.x ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
        run: npm install

      - name: build production project
        run: npm run build:prod

      - name: linting typescript
        run: npm run lint:ts

      - name: linting styles
        run: npm run lint:scss

      - name: unit testing
        run: npm run test:unit
